## BONUS MATERIALS

- Run models without degree correction to see what those results are?

# Model 5: Weighted, Poisson-distributed, Refined, Marginalized, with Additional Covariates

are in fact other things we could do keep improving our model within the iterative framework of Box's loop, or Wickham's loop. As I discussed in the recorded lecture, this is exactly how Bayesian Data Analysis (BDA) is done; it's a Bayesian workflow (cites here). Before stopping, we are going to fit one last model. This time, we'll include additional node and edge attributes as covariates in our model. To this point, we have used *only* relational / structural information about edges to fit this model; let's see if the inclusion of this additional information improves things further.



### Models 6-9: Model Misspecification and Transformations

- We can apply transformations to the distributions to make them more appropriate (e.g. Poisson with with Gamma-distributed rate parameter to simulate overdispersion and approximate a NB distribution)
- We can transform the observed data to make them conform to the model expectations better (log them?)
- We can misspecify models and still get statistically reasonable results (real-exponential)
- In this section, we consider those options.

> Have I made a mistake here maybe? This is not what I would have expected. Should I try the mis-specified model with real-exponential and see if I get the same results Tyler did?

- Why are we trying the `real-exponential` here?

```{python}
model_2B = gt.minimize_nested_blockmodel_dl(g,
    state_args = dict(
        recs=[g.ep.edge_weight],
        rec_types = ['real-exponential']
    )
)
```

```{python}
m2B_mdl = model_2B.entropy()
model_mdl_scores["Model 2B"] = int(round(m2B_mdl))
pprint(model_mdl_scores)
```

> The `real-exponential` model is better, but still worse than the binary network! WTF!
> Could this possibly be because I am using the same `g` and not `g.copy()`?
> No, it doesn't have anything to do with deep copies. I just tested it.
> I am going to proceed with drafting this notebook and will return to the model scores once I have a draft


# Model 10: Planted Partition Models


# END SANITY CHECK HERE... MOVE ON...



### Comparing Nested SBMs with Bad Modularity-Maximization Approaches
