<br>

:::: {.columns}
::: {.column width="30%"}
### Today
Agent-based modelling with [Mesa]{.kn-pink}
:::

::: {.column width="5%"}
:::

::: {.column width="65%"}
1. What are agent-based [(individual-based)]{.nord-light} models?<br>[From equation-based models to agent-based models<br>Example: SIR models of disease diffusion]{.nord-footer}
2. Designing, documenting, and developing ABMs<br>[The agent-based modelling cycle]{.nord-footer}
3. Model design concepts and pattern-oriented modelling
4. Developing your first ABM in Mesa<br>[OOP and Mesa 101<br>Extended example: developing a SIR model]{.nord-footer}
5. Analyzing an ABM<br>[Parameter sweeps and sensitivity analysis]{.nord-footer}
6. Social Learning, Influence, and Opinion Dynamics<br>[Bounded confidence models]{.nord-footer}
7. Reduction, Realism, and Model Trade-offs<br>[$\longleftarrow$ Fine-grained vs. course-grained models $\longrightarrow$<br>What's hot now?]{.nord-footer}
:::
::::



##

<br>

:::: {.columns}
::: {.column width="30%"}
### Approach
Python, R
:::

::: {.column width="55%"}
I will spend a lot of time explaining how the models are implemented in Python, but the primary [learning objectives]{.kn-pink} are to

<br>

1. understand these models conceptually
2. set up their inputs and
3. analyze their outputs within a theoretical or applied context

<br>

**If you are in the R course**, focus on the logic of the Python code to better understand the models themselves; there is no expectation that you will "learn Python." Johannes will still show you how to setup, run, and analyze these models using R.
:::

::: {.column width="15%"}
:::
::::
