# Why Simulate?

## Foundations of Interative Agent-based Modelling

[[@macy2002factors; @squazzoni2012agent; @bruch2015agent; @wilensky2015introduction; @crooks2018agent; @railsback2019agent; @smaldino2023modeling]]{.nord-footer}

## The Modelling Cycle

<br>

:::: {.columns}
::: {.column width="45%"}
![The ABM modelling cycle. [Figure reproduced from @railsback2019agent.]{.nord-light}](media/abm-cycle.png){width=100% #fig-abm-cycle}
:::

::: {.column width="10%"}
:::

::: {.column width="45%"}
@railsback2019agent offer a useful 6-part framework for iterative agent-based modelling.

1. Formulate the question
2. Assemble hypotheses for essential processes and structure
3. Choose scales, entities, state variables, processes, and parameters
4. Implement the model
5. Analyze, test, and revise the model<br>[(recall the Box and Wickham loops!)]{.nord-footer}
6. Communicate the model
:::
::::

## The ODD Protocol

- We will come back to this, but here is a high-level overview to prime you for what's coming.

## Model Design Concepts

:::: {.columns}
::: {.column width="45%"}
More useful stuff from @railsback2019agent that we will touch on throughout the lecture and revisit at the end when we talk about the ODD protocol.
:::

::: {.column width="10%"}
:::

::: {.column width="45%"}
1. Emergence
2. Observation
3. Sensing
4. Adaptive Behaviour and Objectives
5. Prediction
6. Interaction
7. Scheduling
8. Stochasticity
9. Collectives
:::
::::

## Pattern-oriented Modelling

More @railsback2019agent. What are the key points for each of these summarized at a high-level?

- patterns for model structure
- theory development
- parameterization and calibration

## Model Analysis

- designing, implementing, and testing models is just the start
- summarize key points from:
    - analyzing and understanding ABMs
    - sensitivity, uncertainty, and robustness analysis